apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.container.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
      restartPolicy: Never
  backoffLimit: {{ .Values.job.backoffLimit }}